### PR TITLE
Test workflow

### PR DESCRIPTION
**Pull request by dmone90**
Trigger builds on PR opening and when merged to master.
Handled by two separate jobs

### CODE REVIEW

**Comment by dmone90** [comment]
rerun

**Comment by dmone90** [comment]
rerun

**Comment by dmone90** [comment]
rerun

**Comment by dmone90** [comment]
rerun

**Comment by dmone90** [comment]
rerun

**Comment by dmone90** [comment]
rerun

**Comment by dmone90** [comment]
rerun

**Comment by dmone90** [comment]
rerun

**Comment by dmone90** [comment]
rerun

**Comment by dmone90** [comment]
rerun

**Comment by dmone90** [comment]
rerun

**Comment by dmone90** [comment]
rerun

**Comment by dmone90** [comment]
rerun

**Comment by dmone90** [comment]
rerun

**Comment by dmone90** [comment]
rerun

**Comment by dmone90** [comment]
rerun

**Comment by dmone90** [comment]
rerun

**Comment by dmone90** [comment]
rerun

**Comment by atyponci** [comment]
Can one of the admins verify this patch?

**Comment by dmone90** [comment]
add to whitelist

**Comment by dmone90** [comment]
rerun

**Comment by dmone90** [comment]
rerun

**Comment by dmone90** [comment]
ok to test

**Comment by dmone90** [comment]
rerun

**Pull request merged**
